### ISSUE TITLE
Проверка ДЗ

### ISSUE THREAD

**Issue by alexey-ershkov** [AlexeyErshov999/filmopoisk#2]
# Проверка ДЗ

## Базовые требования:
- Создан github-репозиторий, в нём есть README, gitignore, установлены все необходимые зависимости  - **5**
- Проект запускается - **5**
- Вёрстка соответствует дизайн-макетам (допускаются минимальные отхождения, адаптив не требуется) - **4**

### Шапка
 - Позиционируется липко (стики) - **2**

### Авторизация

- Для реализации модального окна используется портал  - **0**
- После успешной авторизации кнопка «Войти» меняется на заглушку иконки пользователя и кнопку «Выйти» - **0**
- Сохраняем авторизационный токен из ответа ручки бэка (например, в localStorage) - **0**
- В идеале, работать с токеном через thunk (где-то в мидлваре) - **0**
- По клику на кнопку «Выйти» удаляем токен и снимает авторизацию - **0** 
- При инициализации приложения проверяем авторизационный токен - **0**

### Реализована страница списка фильмов 

- Поиск происходит во время ввода пользователем символов. Дёргаем ручку /search - **0**
- Реализованы фильтры с dropdown - **0**
- Сохранять фильтры в query-params - **0**
- Реализован список фильмов с пагинацией - **1**

### Страница фильма 

- Дёргаем ручку /movie - **4**
- Соответствующие данные отрисованы - **3**
- Есть запрос за получением оценки для фильма - **0**
- Если пользователь авторизован, даём возможность поставить оценку — запрос мутации - **0**
- После выставления оценки обновляем кеш запроса /movie - **0**

### Общий функционал

- Реализовать единообразную обработку ошибок для запросов - **0**
- Реализован лоадер - **0**
- Используем debounce для поиска фильма и выставления оценки - **0**

### Стор

- Используется rtk и rtk-query- **0**
- Данные корректно разбиты на модули (пример — авторизация, searchParams из фильтров) - **0**
- Селекторы написаны оптимально (нет кучи дублирования) - **0**

### Миграция на Next

- Реализована миграция с использованием SSR - **0**
- Для картинок используется Image некста. Скрины фильма, которые вне вьюпорта грузятся лениво  - **0**
- Страница фильма реализована с помощью Dynamic Routes - **0**

## Итого баллов
24 балла

## Комментарии по ревью
Приветы) много из задания не сделано

Верстке немного плохо - хедер поехал относительно горизонтальной оси

В архитектуре не отделены никак компоненты рендерилки и компоненты с логикой, закидывать все в папку components не лучшая практика

Круто, что заиспользовал pnpm) Но не хватило nvmrc файлов для понимания какая нода нужна и описания в package.json какой pnpm нужен

**Comment by AlexeyErshov999** [comment]
Привет! Спасибо за ревью! Я после сдачи только понял, что не запушил последний коммит с фичами, поэтому ты проверял не все, что сделано. Это грустно, конечно. Но это моя ошибка)
